### ISSUE TITLE
field required (type=value_error.missing)

### ISSUE THREAD

**Issue by mbnoimi** [jonra1993/fastapi-alembic-sqlmodel-async#2]
After executing `docker compose up --build` this error keeps running forever

How can fix it please?

```
nginx           | 2022/07/25 09:21:32 [notice] 1#1: start worker process 32
traefik-proxy   | time="2022-07-25T09:21:33Z" level=info msg="Configuration loaded from file: /traefik.yml"
fastapi_server  | Traceback (most recent call last):
fastapi_server  |   File "/usr/local/bin/alembic", line 8, in <module>
fastapi_server  |     sys.exit(main())
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 588, in main
fastapi_server  |     CommandLine(prog=prog).main(argv=argv)
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 582, in main
fastapi_server  |     self.run_cmd(cfg, options)
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/config.py", line 559, in run_cmd
fastapi_server  |     fn(
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 320, in upgrade
fastapi_server  |     script.run_env()
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 563, in run_env
fastapi_server  |     util.load_python_file(self.dir, "env.py")
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
fastapi_server  |     module = load_module_py(module_id, path)
fastapi_server  |   File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
fastapi_server  |     spec.loader.exec_module(module)  # type: ignore
fastapi_server  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
fastapi_server  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
fastapi_server  |   File "alembic/env.py", line 7, in <module>
fastapi_server  |     from app.core.config import Settings
fastapi_server  |   File "/code/app/core/config.py", line 51, in <module>
fastapi_server  |     settings = Settings()
fastapi_server  |   File "pydantic/env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
fastapi_server  |   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
fastapi_server  | pydantic.error_wrappers.ValidationError: 1 validation error for Settings
fastapi_server  | REDIS_PORT
fastapi_server  |   field required (type=value_error.missing)
fastapi_server exited with code 1
```

**Comment by mbnoimi** [comment]
**.env**
```env
#############################################
# FastAPI environment variables
#############################################
PROJECT_NAME=fastapi-sqlmodel-alembic
FIRST_SUPERUSER_PASSWORD=admin
FIRST_SUPERUSER_EMAIL=admin@admin.com
ENCRYPT_KEY=TshgGacKPYrm35m89UqbRg46JAbUm2yRtxOCQFdqa3w=
SECRET_KEY=09d25e0sas4faa6c52gf6c818166b7a9563b93f7sdsdef6f0f4caa6cf63b88e8d3e7
BACKEND_CORS_ORIGINS=["*"] 

#############################################
# PostgreSQL database environment variables
#############################################
DATABASE_HOST=database
DATABASE_USER=postgres
DATABASE_PASSWORD=postgres
DATABASE_NAME=foo
DATABASE_PORT=5432

#############################################
# Traefik variables
#############################################
EXT_ENDPOINT1=mycustomwebsite.com
LOCAL_1=localhost
LOCAL_2=127.0.0.1

#############################################
# Redis variables
#############################################
REDIS_HOST=redis_server
REDIS_HOST_PORT=6359
```

**docker-compose.yml**
```yml
version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    build: ./project
    restart: always
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'"
    volumes:
      - ./project:/code
    expose:
      - "8000"
    env_file: ".env"
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi_local.entrypoints=web"
      - "traefik.http.routers.fastapi_local.rule=Host(`fastapi.${LOCAL_1}`, `fastapi.${LOCAL_2}`, `fastapi.${EXT_ENDPOINT1}`)"
      - traefik.http.services.fastapi_localservice.loadbalancer.server.port=8000
  
  database:
    image: bitnami/postgresql:13.3.0
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql
    ports:
      - 5454:5432  # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"
      - POSTGRESQL_POSTGRES_PASSWORD= ${DATABASE_PASSWORD}
      
  redis_server:
    container_name: redis_server
    image: "redis:alpine"
    restart: always
    expose:
      - "6359"
    env_file: .env

  traefik-proxy:
    container_name: traefik-proxy
    restart: always
    image: "traefik:latest"
    command:
      - "--providers.docker=true"
    expose:
      - 80
    depends_on:      
      - fastapi_server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/.htpasswd:/.htpasswd
      - "${EB_LOG_BASE_DIR:-./traefik}/traefik-proxy:/logs"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${LOCAL_1}`, `traefik.${LOCAL_2}`, `traefik.${EXT_ENDPOINT1}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/.htpasswd"

  nginx:
    container_name: nginx
    restart: unless-stopped
    logging:
      driver: none
    image: "nginx:latest"
    ports:
      - "80:8080"
    volumes:
      - ./static:/code/static
      - ./nginx-config-files/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config-files/app.nginx.template:/etc/nginx/templates/app.nginx.template
      - "${EB_LOG_BASE_DIR:-./nginx-config-files}/nginx-proxy:/var/log/nginx"
```
